{
  imports = [
    ./hardware.nix
    ./disk-config.nix
    ./sops.nix
    ./provision.nix
    ./virtualisation.nix
    ./llama-server.nix
    ./hindsight-embed.nix
    ./hindsight-memory.nix
    ./agentmemory.nix
    ./netdata.nix
    ./omp-auth-gateway.nix
    ../../modules/system.nix
    ../../modules/packages.nix
    ../../modules/home-manager.nix
    ../../modules/hermes-agent.nix
    ../../modules/hermes-plugins.nix
    ../../modules/users.nix
  ];
}
